# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98fe2d4ee3a3f31640ec12830b55c055a91e4198875bf765ff1e0f536ce1974eba3df251724a6a7cb16aecc0c2d9f343e731692d2bfdd5c26e8197d49d1b7136

test:
  secret_key_base: c7a1324f6cac5b161717c8007b67b8607e5dad9e96df1c63ac59550b0391e94e30ac5dff189aa40f88a7335f8c964dc07cdac2829a4c0e898499102eb4bc76c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
